package:
  name: tospax
  version: 0.0.1

source:
  git_tag:
  git_url: https://github.com/benprofessionaledition/stylegan.git

build:
  noarch: python
  script: python3 setup.py install bdist_wheel

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pytorch
    - torchvision
    - tensorboard
    - numpy
    - pandas
    - matplotlib
    - IPython
    - tqdm

test:

  imports:
    - torch
    - torchvision
  commands:
    - python3 -m unittest .


about:
  home: https://github.com/benprofessionaledition/stylegan
  summary: some stylegan shit